batch_size: 4
test_batch_size: 1
epoch: 1000
learning_rate: 1e-3
gpu: 0

num_point: 4096
optimizer: Adam
weight_decay: 1e-4
normal: True
lr_decay: 0.5
step_size: 20

defaults:
  - model: Hengshuang

hydra:
  run:
    dir: log/partseg/${model.name}

  sweep:
    dir: log/partseg
    subdir: ${model.name}


